
services:
  nodejs:
    image: "node:20.12-bookworm"
    container_name: app-nodejs-bookworm
    restart: always
    user: "node"
    working_dir: /home/node/app
    # entrypoint: /bin/bash
    environment:
      - NODE_ENV=development
    ports:
      - 5173:5173 #vue
    volumes:
      - ./:/home/node/app
    tty: true
    # package.json "scripts": {"dev": "vite --host"}
#     networks:
#       - buyer-backend_buyer_network

# networks:
#   buyer-backend_buyer_network:
#       external: true


